### ISSUE TITLE
Add notifications

### ISSUE THREAD

**Issue by fatlotus** [codeu-2018-team12/codeu-2018-team12#37]
This one is a bit more nebulous. One possible way to approach it would be:

- [ ] Add support for storing the user's email in the `User` class.
- [ ] Fill in the email on registration.
- [ ] Send an email when there is a new message.

Might be nice to elide messages in case the user is already signed in (or something).

**Comment by Mariamcm90** [comment]
I'm not really sure how to do this yet, but I'd be interested in trying to figure it out after more progress is made on the activity feed!

**Comment by Mariamcm90** [comment]
Just adding that if anyone else is interested wants to work on this as well, feel free to! :) Or we can work on it together.
