### ISSUE TITLE
Week 0: Edit about.jsp to include information about the team.

### ISSUE THREAD

**Issue by fatlotus** [codeu-2018-team12/codeu-2018-team12#4]
This way, we can make it our own!

I think Maria was working on this one.

**Comment by Mariamcm90** [comment]
Sounds good! Should I keep adding to the page to make it more custom then? I know as of now it only has some added text. I can get everyone's ideas about how it should look and then tailor it to that!

**Comment by fatlotus** [comment]
Up to you! I think the point is just to get familiar with Github.

**Comment by Mariamcm90** [comment]
Sure thing. Thanks!
