### ISSUE TITLE
Settings Page

### ISSUE THREAD

**Issue by mariezimmy** [codeu-2018-team12/codeu-2018-team12#61]
(maybe save for later, once notifications functionality completed)
- [x]  Enable users to opt in or out of email notifications 
- [x]  Choose frequency of notifications 
- [x]  Give users the opportunity to choose how their activity feed is presented (I guess this is up to interpretation). Maybe how many notifications they see, what types, etc.

- Allow a user to adjust how they receive their notifications
- Other settings?

**Comment by Mariamcm90** [comment]
I think it might be good to create the page and then add settings as we add more features that can be customized! Maybe initially users can choose their preferences about the way their activity feed is presented and how frequently/if they want to receive email notifications, and then we can add from there.

**Comment by fatlotus** [comment]
So, what's left here?
