### ISSUE TITLE
Privacy

### ISSUE THREAD

**Issue by mariezimmy** [codeu-2018-team12/codeu-2018-team12#62]
This is open for interpretation, but let's address some privacy concerns!
- [x] Populate activity feed with alerts pertaining to the logged in user (i.e. show messages from the conversations the user has joined, not all conversations)
- [x] If a user has not joined a conversation, do not allow the user to see the conversation messages
- [x] Incorporate privacy settings to settings page (will be completed once settings page set up)

Other things to consider (for implementation now or later):
- What do we want non-logged in users to see?
        - Can they see people's profiles? Can they see conversations?
- What do we want logged in users to see?

**Comment by mariezimmy** [comment]
Feel free to add stuff to this one! I was just brainstorming!

**Comment by mariezimmy** [comment]
Also, others feel free to work on this with me if you want!

**Comment by Mariamcm90** [comment]
Maybe we can also link this to the settings page (e.g. users can specify what info they want or don't want to be shared)? Just a suggestion!

**Comment by mariezimmy** [comment]
I like that idea! I'll edit the issue!

**Comment by kkane098** [comment]
I believe my implementation for direct messages will cover most of "If a user has not joined a conversation, do not allow the user to see the conversation messages", I can probably just finish that part of it off if you want.

**Comment by mariezimmy** [comment]
@kkane098 Kevin, I just now saw that message! If you want to that's fine. I also have the code written for that as well, but you said you were almost done with direct messages, so I'm fine using your code for that bit!

**Comment by fatlotus** [comment]
So, what's left here?

**Comment by mariezimmy** [comment]
I think the main stuff is done once PR 81 is pushed to master, but there are minor things like how to deal with a user who has not logged in and what we want them to see. I believe, for instance, if a non-logged user tries to go to the settings page, an error occurs because we are trying to pull user data on that page but there's a null user. Things like that! I could create a separate PR for those concerns if need be. I think that maybe falls under the bug label?
